server {
    listen 80;
    server_name pixelatumente.es www.pixelatumente.es;
    location /.well-known/acme-challenge/ {
        root /var/www/acme;
    }
    if ($uri !~ '^/\.well-known/acme-challenge/') {
        return 301 https://pixelatumente.es$request_uri;
    }
}
